### ISSUE TITLE
Mainitaan YSO:n yläkäsitteen poistuminen vaikka ei olekaan poistunut 

### ISSUE THREAD

**Issue by miguelvaara** [NatLibFi/mutu#1]
Saattaa tuottaa tulosteena toimivassa Excel-asiakirjassa, muutostyyppi 3.2:n kohdalla virheellisen tuloksen rdfs:subClassOf-tyyppisissä suhteissa. 

Muutoksen kuvauksessa sanotaan, että käsitteeltä on poistunut uudessa YSO:ssa yläkäsite, vaikka se edelleen on olemassa.

Lisätietoja ongelmasta:
@kouralex
@miguelahonen

**Comment by miguelvaara** [comment]
Tällä komennolla Mutu ajettiin, kun ongelma ilmeni:
java -jar mutu.jar -domainOnt github_soto.ttl github_yso-soto.ttl -newYso dev-yso-skos-diotima.ttl -domainOntUri http://finto.fi/soto/ -newYsoUri http://dev.finto.fi/ysodiotima/

**Comment by devseppala** [comment]
En pysty itse toistamaan tätä ongelmaa Githubista (Finto-data/vocabularies) ladatuilla aineistoilla. Selvännäkijä kykyni sanovatkin, että olet tehnyt vertailun Diotiman skosifioituun julkaisuversioon eikä kehitysversioon ;)

**Comment by miguelvaara** [comment]
Hienoa kun tämä ratkesi :-) ja kysessä oli meidän osaltamme väärinkäsitys, väärä tapa toimia. Nyt testasimme, käytimme GitHubin Diotimaa ja Excel-työkirja muodostui oikein.
